[tool.poetry]
name = "sb-database"
version = "0.1.0"
description = ""
authors = ["PabloLec <pablolec@pm.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
